CREATE TABLE tasks (
id BINARY(16) NOT NULL,
title VARCHAR(255) NOT NULL,
description TEXT NULL,
completed BOOLEAN NOT NULL DEFAULT FALSE,
created_at TIMESTAMP NOT NULL,
updated_at TIMESTAMP NOT NULL,
is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
sync_status VARCHAR(32) NOT NULL DEFAULT 'synced',
server_id VARCHAR(64) NULL,
last_synced_at TIMESTAMP NULL,
PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;